name: Linux-CI

on:
  workflow_dispatch:
  push:
    branches:
      - py313_SET_FUNCTION_ATTRIBUTE
  pull_request:
    branches:
      - py313_SET_FUNCTION_ATTRIBUTE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: py313_SET_FUNCTION_ATTRIBUTE

      - name: Configure and Build
        run: |
          mkdir -p build-debug build-release

          (
            cd build-debug
            cmake -DCMAKE_BUILD_TYPE=Debug ..
            make -j$(nproc)
          )

          (
            cd build-release
            cmake -DCMAKE_BUILD_TYPE=Release ..
            make -j$(nproc)
          )

      - name: Test
        run: |
          cmake --build build-debug --target check || true
          cmake --build build-release --target check || true

      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-debug-artifacts
          path: build-debug/

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-release-artifacts
          path: build-release/
